[build]
  command = "npm run build"
  publish = "dist"

[functions]
  directory = "netlify/functions"
  
[[redirects]]
  from = ".well-known/assetlinks.json"
  to = "/.netlify/functions/assetlinks"
  status = 200
  
  from = "/*"
  to = "/index.html"
  status = 200
  